-- This file uses an intentionally invalid schema version for negative testing

BEGIN TRANSACTION;
INSERT INTO bioactive_agent_type VALUES(1,'prescription medication');
INSERT INTO bioactive_agent_type VALUES(2,'over-the-counter (OTC) medication');
INSERT INTO bioactive_agent_type VALUES(3,'dietary supplement');

INSERT INTO unit_category VALUES(1,'mass');
INSERT INTO unit_category VALUES(2,'volume');
INSERT INTO unit_category VALUES(3,'concentration');
INSERT INTO unit_category VALUES(4,'potency');
INSERT INTO unit_category VALUES(5,'frequency');
INSERT INTO unit_category VALUES(6,'infusion rate');
INSERT INTO unit_category VALUES(7,'unit form');
INSERT INTO unit_category VALUES(8,'portion');

INSERT INTO unit VALUES(1,'microgram','micrograms','mcg');
INSERT INTO unit VALUES(2,'milligram','milligrams','mg');
INSERT INTO unit VALUES(3,'gram','grams','g');
INSERT INTO unit VALUES(4,'kilogram','kilograms','kg');
INSERT INTO unit VALUES(5,'nanogram','nanograms','ng');
INSERT INTO unit VALUES(6,'picogram','picograms','pg');
INSERT INTO unit VALUES(7,'microliter','microliters','mcL');
INSERT INTO unit VALUES(8,'milliliter','milliliters','mL');
INSERT INTO unit VALUES(9,'liter','liters','L');
INSERT INTO unit VALUES(10,'deciliter','deciliters','dL');
INSERT INTO unit VALUES(11,'milligrams per milliliter','milligrams per milliliter','mg/mL');
INSERT INTO unit VALUES(12,'micrograms per milliliter','micrograms per milliliter','mcg/mL');
INSERT INTO unit VALUES(13,'nanograms per milliliter','nanograms per milliliter','ng/mL');
INSERT INTO unit VALUES(14,'milligrams per liter','milligrams per liter','mg/L');
INSERT INTO unit VALUES(15,'millimoles per liter','millimoles per liter','mmol/L');
INSERT INTO unit VALUES(16,'milliequivalents per liter','milliequivalents per liter','mEq/L');
INSERT INTO unit VALUES(17,'units per milliliter','units per milliliter','U/mL');
INSERT INTO unit VALUES(18,'percent concentration (weight/volume)','percent concentration (weight/volume)','% (w/v)');
INSERT INTO unit VALUES(19,'international unit','international units','IU');
INSERT INTO unit VALUES(20,'unit','units','U');
INSERT INTO unit VALUES(21,'milliequivalent','milliequivalent','mEq');
INSERT INTO unit VALUES(22,'once daily','once daily','QD');
INSERT INTO unit VALUES(23,'twice a day','twice a day','BID');
INSERT INTO unit VALUES(24,'three times a day','three times a day','TID');
INSERT INTO unit VALUES(25,'four times a day','four times a day','QID');
INSERT INTO unit VALUES(26,'every 4 hours','every 4 hours','q4h');
INSERT INTO unit VALUES(27,'as needed','as needed','prn');
INSERT INTO unit VALUES(28,'at bedtime','at bedtime','hs');
INSERT INTO unit VALUES(29,'before meals','before meals','ac');
INSERT INTO unit VALUES(30,'after meals','after meals','pc');
INSERT INTO unit VALUES(31,'milliliters per hour','milliliters per hour','mL/h');
INSERT INTO unit VALUES(32,'drops per minute','drops per minute','gtt/min');
INSERT INTO unit VALUES(33,'micrograms per kilogram per minute','micrograms per kilogram per minute','mcg/kg/min');
INSERT INTO unit VALUES(34,'milligrams per kilogram per hour','milligrams per kilogram per hour','mg/kg/h');
INSERT INTO unit VALUES(35,'spray','sprays',NULL);
INSERT INTO unit VALUES(36,'actuation','actuation',NULL);
INSERT INTO unit VALUES(37,'puff','puffs',NULL);
INSERT INTO unit VALUES(38,'drop','drops','gtt');
INSERT INTO unit VALUES(39,'suppository','suppositories','supp');
INSERT INTO unit VALUES(40,'patch','patches',NULL);
INSERT INTO unit VALUES(41,'tablet','tablets','tab');
INSERT INTO unit VALUES(42,'capsule','capsules','cap');
INSERT INTO unit VALUES(43,'teaspoon','teaspoons','tsp');
INSERT INTO unit VALUES(44,'tablespoon','tablespoons','tbsp');
INSERT INTO unit VALUES(45,'fluid ounce','fluid ounces','fl oz');
INSERT INTO unit VALUES(46,'cup','cups',NULL);
INSERT INTO unit VALUES(47,'softgel','softgels',NULL);
INSERT INTO unit VALUES(48,'lozenge','lozenges',NULL);
INSERT INTO unit VALUES(49,'gummy','gummies',NULL);
INSERT INTO unit VALUES(50,'chewable','chewables',NULL);
INSERT INTO unit VALUES(51,'scoop','scoops',NULL);
INSERT INTO unit VALUES(52,'stick pack','stick packs','stick');
INSERT INTO unit VALUES(53,'packet','packets','pkt');
INSERT INTO unit VALUES(54,'shot','shots',NULL);
INSERT INTO unit VALUES(55,'percent daily value','percent daily value','%DV');
INSERT INTO unit VALUES(56,'serving','servings',NULL);

INSERT INTO categorized_unit VALUES(1,1);
INSERT INTO categorized_unit VALUES(2,1);
INSERT INTO categorized_unit VALUES(3,1);
INSERT INTO categorized_unit VALUES(4,1);
INSERT INTO categorized_unit VALUES(5,1);
INSERT INTO categorized_unit VALUES(6,1);
INSERT INTO categorized_unit VALUES(7,2);
INSERT INTO categorized_unit VALUES(8,2);
INSERT INTO categorized_unit VALUES(9,2);
INSERT INTO categorized_unit VALUES(10,2);
INSERT INTO categorized_unit VALUES(11,3);
INSERT INTO categorized_unit VALUES(12,3);
INSERT INTO categorized_unit VALUES(13,3);
INSERT INTO categorized_unit VALUES(14,3);
INSERT INTO categorized_unit VALUES(15,3);
INSERT INTO categorized_unit VALUES(16,3);
INSERT INTO categorized_unit VALUES(17,3);
INSERT INTO categorized_unit VALUES(18,3);
INSERT INTO categorized_unit VALUES(19,4);
INSERT INTO categorized_unit VALUES(20,4);
INSERT INTO categorized_unit VALUES(21,4);
INSERT INTO categorized_unit VALUES(22,5);
INSERT INTO categorized_unit VALUES(23,5);
INSERT INTO categorized_unit VALUES(24,5);
INSERT INTO categorized_unit VALUES(25,5);
INSERT INTO categorized_unit VALUES(26,5);
INSERT INTO categorized_unit VALUES(27,5);
INSERT INTO categorized_unit VALUES(28,5);
INSERT INTO categorized_unit VALUES(29,5);
INSERT INTO categorized_unit VALUES(30,5);
INSERT INTO categorized_unit VALUES(31,6);
INSERT INTO categorized_unit VALUES(32,6);
INSERT INTO categorized_unit VALUES(33,6);
INSERT INTO categorized_unit VALUES(34,6);
INSERT INTO categorized_unit VALUES(35,7);
INSERT INTO categorized_unit VALUES(36,7);
INSERT INTO categorized_unit VALUES(37,7);
INSERT INTO categorized_unit VALUES(38,7);
INSERT INTO categorized_unit VALUES(39,7);
INSERT INTO categorized_unit VALUES(40,7);
INSERT INTO categorized_unit VALUES(41,7);
INSERT INTO categorized_unit VALUES(42,7);
INSERT INTO categorized_unit VALUES(43,2);
INSERT INTO categorized_unit VALUES(44,2);
INSERT INTO categorized_unit VALUES(45,2);
INSERT INTO categorized_unit VALUES(46,2);
INSERT INTO categorized_unit VALUES(47,7);
INSERT INTO categorized_unit VALUES(48,7);
INSERT INTO categorized_unit VALUES(49,7);
INSERT INTO categorized_unit VALUES(50,7);
INSERT INTO categorized_unit VALUES(51,7);
INSERT INTO categorized_unit VALUES(52,7);
INSERT INTO categorized_unit VALUES(53,7);
INSERT INTO categorized_unit VALUES(54,7);
INSERT INTO categorized_unit VALUES(55,4);
INSERT INTO categorized_unit VALUES(56,8);

-- This project expects 0.1.0 and higher as recommended in the semantic 
-- versioning rules.
INSERT INTO database_release VALUES (1, "0.0.0", unixepoch('now'));

COMMIT;
